apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: front-app
  name: front-app
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: front-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: front-app
    spec:
      containers:
      - image: hugocf/front-app:0.2
        imagePullPolicy: IfNotPresent
        name: front-app
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
