apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: front-app
  name: front-app
  selfLink: /api/v1/namespaces/default/services/front-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: front-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
